require_relative '../src/book'
require_relative '../src/classroom'
require_relative '../src/rental'
require_relative '../src/person'
require_relative '../src/student'
require_relative '../src/teacher'
require_relative '../src/corrector'
